### ISSUE TITLE
services.xserver.displayManager.sddm.theme = "nixos"

### ISSUE THREAD

**Issue by kametaro** [MarianArlt/nixos-sddm-theme#1]
Hi

It is a wonderful theme! so I want to use it.
Can I set the following in configuration.nix?

services.xserver.displayManager.sddm.theme = "nixos"

Thanks.

**Comment by MarianArlt** [comment]
Please refer to the [README](https://github.com/MarianArlt/nixos-sddm-theme#installing). The safest way to install this theme is to use the system settings. This requires the `sddm-kcm` package to be installed (system settings configuration module for SDDM). For NixOS you can install the package with `nix-env -i sddm-kcm`

**Comment by IvanMalison** [comment]
@MarianArlt Seems pretty strange that a "nixos" theme doesn't have an easy way to install through configraution.nix. Can you clarify why that is?

**Comment by MarianArlt** [comment]
Yes @IvanMalison I can. When I made this theme I was thinking about a nice swinging name for it and came up with NixOS in my mind (apparently referring to MacOS). I didn't know back then that there was a whole linux distribution called that way. I am actually considering to rename my theme soon since it's a reason for confusion.

**Comment by w4** [comment]
Just in case anyone stumbles across this issue, changing your SDDM theme is pretty easy in NixOS, just point it to the path of the theme:

```nix
services.xserver.displayManager.sddm.theme = "${(pkgs.fetchFromGitHub {
    owner = "MarianArlt";
    repo = "kde-plasma-chili";
    rev = "a371123959676f608f01421398f7400a2f01ae06";
    sha256 = "17pkxpk4lfgm14yfwg6rw6zrkdpxilzv90s48s2hsicgl3vmyr3x";
})}";
```

`sddm-kcm` doesn't work without making your Nix store writable, which is the wrong solution to any Nix-related issue :P

**Comment by byrmn** [comment]
> Just in case anyone stumbles across this issue, changing your SDDM theme is pretty easy in NixOS, just point it to the path of the theme:
> 
> ```nix
> services.xserver.displayManager.sddm.theme = "${(pkgs.fetchFromGitHub {
>     owner = "MarianArlt";
>     repo = "kde-plasma-chili";
>     rev = "a371123959676f608f01421398f7400a2f01ae06";
>     sha256 = "17pkxpk4lfgm14yfwg6rw6zrkdpxilzv90s48s2hsicgl3vmyr3x";
> })}";
> ```
> 
> `sddm-kcm` doesn't work without making your Nix store writable, which is the wrong solution to any Nix-related issue :P

You're the best, ive been searching for 7 hours to doit, changing and making something  here and there, and the solution turns out really simple.

but one more thing, since its just get all the file and configuration from git, which including the included wallpaper, what if i want to change the wallpaper? how to do it? thank you :)

**Comment by walseb** [comment]
> > Just in case anyone stumbles across this issue, changing your SDDM theme is pretty easy in NixOS, just point it to the path of the theme:
> > ```nix
> > services.xserver.displayManager.sddm.theme = "${(pkgs.fetchFromGitHub {
> >     owner = "MarianArlt";
> >     repo = "kde-plasma-chili";
> >     rev = "a371123959676f608f01421398f7400a2f01ae06";
> >     sha256 = "17pkxpk4lfgm14yfwg6rw6zrkdpxilzv90s48s2hsicgl3vmyr3x";
> > })}";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `sddm-kcm` doesn't work without making your Nix store writable, which is the wrong solution to any Nix-related issue :P
> 
> You're the best, ive been searching for 7 hours to doit, changing and making something here and there, and the solution turns out really simple.
> 
> but one more thing, since its just get all the file and configuration from git, which including the included wallpaper, what if i want to change the wallpaper? how to do it? thank you :)

In case you haven't found a solution to this, easiest would probably be to add in the wallpaper during the install phase. Example with another SDDM theme:
```
{ pkgs }:

let
  imgLink = "https://YOURIMAGELINK/image.png";

  image = pkgs.fetchurl {
    url = imgLink;
    sha256 = "sha256-HrcYriKliK2QN02/2vFK/osFjTT1NamhGKik3tozGU0=";
  };
in
pkgs.stdenv.mkDerivation {
  name = "sddm-theme";
  src = pkgs.fetchFromGitHub {
    owner = "MarianArlt";
    repo = "sddm-sugar-dark";
    rev = "ceb2c455663429be03ba62d9f898c571650ef7fe";
    sha256 = "0153z1kylbhc9d12nxy9vpn0spxgrhgy36wy37pk6ysq7akaqlvy";
  };
  installPhase = ''
    mkdir -p $out
    cp -R ./* $out/
    cd $out/
    rm Background.jpg
    cp -r ${image} $out/Background.jpg
   '';
}
```
Source: https://github.com/vimjoyer/theming-video/blob/main/README.md
