### ISSUE TITLE
Can't change backgroud image .

### ISSUE THREAD

**Issue by Hi-Shan** [MarianArlt/nixos-sddm-theme#2]
KDE 5.44.0 / Plasma 5.12.3
can't change backgroud image.

**Comment by MarianArlt** [comment]
Can you change the background image when using the default breeze theme? Works as expected on my machine with Arch 4.15.15 / Plasma 5.12.4 and KDE 5.45

**Comment by Hi-Shan** [comment]
no , can't .. 
i arc and breeze themes none of them .
i find the directory of the background and i replace it , but it still doesn't works..

**Comment by Hi-Shan** [comment]
ok, got it . thanks.. 
Is anyway i can desgin my own background ?
