### ISSUE TITLE
Lockscreen

### ISSUE THREAD

**Issue by romanlex** [MarianArlt/nixos-sddm-theme#3]
Could you make nixos lockscreen :)

**Comment by MarianArlt** [comment]
I have had people asking this before. Sadly the lock screen of Plasma is still a **core** feature of Plasma and has no easy way of including theming yet. I would like to see this as a Plasma feature in the future but this needs attention on KDE trackers.
I could actually write a modified version but people would have to roll back their file(s) _every time_ Plasma gets updated (which is quite often, sometimes several times a week).
So for the moment that's a no - Sorry ;)

**Comment by romanlex** [comment]
@MarianArlt see `/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/lockscreen`
